#!/usr/bin/env python3
"""
zupt_compensator.py
-------------------
Online gyroscope bias compensation with Zero-Velocity Update (ZUPT).

Features
~~~~~~~~
* Loads initial bias from static calibration YAML (auto-generated by
  gyro_calibrator.py).
* Detects zero-velocity periods from IMU variance AND (optionally) from
  wheel encoder odometry (warthog_velocity_controller/odom).
* While static: updates bias online with Exponential Moving Average.
* While static: zeros out angular_velocity in the published message so
  downstream filters (Madgwick, EKF) see no phantom rotation.
* Publishes diagnostics: current bias, static flag, drift estimate.

Subscribes
~~~~~~~~~~
  /imu/data_raw                          sensor_msgs/Imu
  /warthog_velocity_controller/odom      nav_msgs/Odometry   (optional)

Publishes
~~~~~~~~~
  /imu/data_corrected    sensor_msgs/Imu          – bias-removed IMU
  /imu/bias_status       std_msgs/Float32MultiArray – [bx,by,bz,is_static]
"""

import os
import yaml
import numpy as np
from collections import deque

import rospy
from sensor_msgs.msg import Imu
from nav_msgs.msg import Odometry
from std_msgs.msg import Float32MultiArray


# ─────────────────────────────────────────────────────────────────────────────
class ZUPTCompensator:
    def __init__(self):
        rospy.init_node("zupt_compensator", anonymous=False)

        # ── Load params ───────────────────────────────────────────────────────
        default_cfg = os.path.join(
            os.path.dirname(os.path.abspath(__file__)),
            "..", "config", "gyro_bias.yaml"
        )
        self.bias_file  = rospy.get_param("~bias_file",  default_cfg)
        self.imu_topic  = rospy.get_param("~imu_topic",  "/imu/data_raw")
        self.odom_topic = rospy.get_param("~odom_topic",
                                          "/warthog_velocity_controller/odom")
        self.use_odom   = rospy.get_param("~use_odom", True)

        # ZUPT detection thresholds
        self.accel_var_thresh = rospy.get_param("~accel_var_thresh", 0.02)
        self.gyro_var_thresh  = rospy.get_param("~gyro_var_thresh",  0.001)
        self.odom_vel_thresh  = rospy.get_param("~odom_vel_thresh",  0.02)   # m/s
        self.window_size      = rospy.get_param("~window_size",      50)
        self.static_confirm   = rospy.get_param("~static_confirm",   20)     # samples

        # Bias update
        self.alpha = rospy.get_param("~alpha", 0.01)

        # Zero-out angular velocity when static
        self.zero_gyro_when_static = rospy.get_param("~zero_gyro_when_static", True)

        # ── Load initial bias ─────────────────────────────────────────────────
        self.bias = self._load_bias(self.bias_file)

        # ── State ─────────────────────────────────────────────────────────────
        self.accel_window   = deque(maxlen=self.window_size)
        self.gyro_window    = deque(maxlen=self.window_size)
        self.is_static_imu  = False
        self.is_static_odom = True   # assume static until odom says otherwise
        self.static_counter = 0

        # ── Publishers ────────────────────────────────────────────────────────
        self.pub_imu    = rospy.Publisher("/imu/data_corrected",
                                          Imu, queue_size=10)
        self.pub_status = rospy.Publisher("/imu/bias_status",
                                          Float32MultiArray, queue_size=10)

        # ── Subscribers ───────────────────────────────────────────────────────
        rospy.Subscriber(self.imu_topic, Imu, self._imu_cb, queue_size=200)
        if self.use_odom:
            rospy.Subscriber(self.odom_topic, Odometry,
                             self._odom_cb, queue_size=10)
            rospy.loginfo(f"Using odometry from: {self.odom_topic}")
        else:
            rospy.logwarn("Odometry disabled – static detection by IMU only")

        rospy.loginfo("=" * 55)
        rospy.loginfo(" ZUPT Compensator ready")
        rospy.loginfo(f"  IMU topic   : {self.imu_topic}")
        rospy.loginfo(f"  Bias file   : {self.bias_file}")
        rospy.loginfo(f"  Initial bias: x={self.bias[0]:+.6f} "
                      f"y={self.bias[1]:+.6f} z={self.bias[2]:+.6f}")
        rospy.loginfo(f"  Zero gyro when static: {self.zero_gyro_when_static}")
        rospy.loginfo("=" * 55)

    # ── Bias file ─────────────────────────────────────────────────────────────
    def _load_bias(self, path: str) -> np.ndarray:
        """Load bias from YAML; fall back to zeros if file missing."""
        abs_path = os.path.abspath(path)
        if not os.path.isfile(abs_path):
            rospy.logwarn(f"Bias file not found: {abs_path}")
            rospy.logwarn("Starting with zero bias – run calibrate.launch first!")
            return np.zeros(3)

        with open(abs_path, "r") as f:
            data = yaml.safe_load(f)

        bias = np.array([
            data.get("gyro_bias_x", 0.0),
            data.get("gyro_bias_y", 0.0),
            data.get("gyro_bias_z", 0.0),
        ], dtype=float)

        rospy.loginfo(f"Loaded bias from {abs_path}")
        rospy.loginfo(f"  x={bias[0]:+.6f}  y={bias[1]:+.6f}  z={bias[2]:+.6f}")
        return bias

    # ── Odometry callback ─────────────────────────────────────────────────────
    def _odom_cb(self, msg: Odometry):
        """Mark static from odom if linear+angular velocities are near zero."""
        lv = msg.twist.twist.linear
        av = msg.twist.twist.angular
        speed = np.sqrt(lv.x**2 + lv.y**2 + lv.z**2 +
                        av.x**2 + av.y**2 + av.z**2)
        self.is_static_odom = speed < self.odom_vel_thresh

    # ── IMU static detection ──────────────────────────────────────────────────
    def _detect_static_imu(self) -> bool:
        """Return True if IMU variance is below thresholds."""
        if len(self.gyro_window) < self.window_size:
            return False

        accel_var = np.var(np.array(self.accel_window), axis=0)
        gyro_var  = np.var(np.array(self.gyro_window),  axis=0)

        return (np.all(accel_var < self.accel_var_thresh) and
                np.all(gyro_var  < self.gyro_var_thresh))

    # ── Bias EMA update ───────────────────────────────────────────────────────
    def _update_bias(self):
        """
        Exponential Moving Average update.
        When static, gyro reading ≈ bias → use it to refine estimate.
        """
        measured = np.mean(np.array(self.gyro_window), axis=0)
        delta    = measured - self.bias
        self.bias = self.bias + self.alpha * delta

        if abs(delta[2]) > 1e-5:
            rospy.logdebug(f"[ZUPT] bias updated  Δz={delta[2]:+.7f}  "
                           f"bias_z={self.bias[2]:+.6f} rad/s")

    # ── IMU callback (main loop) ──────────────────────────────────────────────
    def _imu_cb(self, msg: Imu):
        gx = msg.angular_velocity.x
        gy = msg.angular_velocity.y
        gz = msg.angular_velocity.z
        ax = msg.linear_acceleration.x
        ay = msg.linear_acceleration.y
        az = msg.linear_acceleration.z

        # Push raw readings into windows
        self.gyro_window.append([gx, gy, gz])
        self.accel_window.append([ax, ay, az])

        # ── Static detection (IMU + odom combined) ──────────────────────────
        self.is_static_imu = self._detect_static_imu()
        is_static = self.is_static_imu and (
            self.is_static_odom if self.use_odom else True
        )

        if is_static:
            self.static_counter += 1
            # Confirm static for a few cycles before updating bias
            if self.static_counter > self.static_confirm:
                self._update_bias()
        else:
            if self.static_counter > self.static_confirm:
                rospy.loginfo(
                    f"[ZUPT] Motion detected | "
                    f"bias_z={self.bias[2]:+.6f} rad/s  "
                    f"(static for {self.static_counter} samples)"
                )
            self.static_counter = 0

        # ── Build corrected IMU message ──────────────────────────────────────
        out = Imu()
        out.header = msg.header

        # Acceleration unchanged
        out.linear_acceleration   = msg.linear_acceleration
        out.linear_acceleration_covariance = msg.linear_acceleration_covariance

        if is_static and self.zero_gyro_when_static:
            # Robot is confirmed stationary – hard-zero angular velocity
            # so Madgwick / EKF does not accumulate drift at all
            out.angular_velocity.x = 0.0
            out.angular_velocity.y = 0.0
            out.angular_velocity.z = 0.0
        else:
            # Subtract current bias estimate
            out.angular_velocity.x = gx - self.bias[0]
            out.angular_velocity.y = gy - self.bias[1]
            out.angular_velocity.z = gz - self.bias[2]

        # Propagate covariance (add bias uncertainty on diagonal)
        cov = list(msg.angular_velocity_covariance)
        if is_static and self.zero_gyro_when_static:
            # Very tight covariance when we know we're static
            cov = [1e-9, 0, 0,
                   0, 1e-9, 0,
                   0, 0, 1e-9]
        out.angular_velocity_covariance = cov

        out.orientation            = msg.orientation
        out.orientation_covariance = msg.orientation_covariance

        self.pub_imu.publish(out)

        # ── Publish status ───────────────────────────────────────────────────
        status = Float32MultiArray()
        status.data = [
            float(self.bias[0]),
            float(self.bias[1]),
            float(self.bias[2]),
            float(is_static),
            float(self.static_counter),
        ]
        self.pub_status.publish(status)


# ─────────────────────────────────────────────────────────────────────────────
if __name__ == "__main__":
    try:
        node = ZUPTCompensator()
        rospy.spin()
    except rospy.ROSInterruptException:
        pass
